add a flag for dakuten to Shiritori
mistval/kotoba pull request #216
Opened 2022-03-06 22:33 UTC by Riolku

Under this flag, the word きょうし accepts じ to start the next word.

Thanks to  @CBaetz for creating the dakuten table.

2022-03-06 22:34 UTC, Riolku commented
This flag caused some interesting interactions with the other flags. I've made notes where useful to talk about issues that came up, and ordering of processing, I also tested it quite a bit locally. Let me know if you have any concerns!

2022-03-08 00:18 UTC, mistval requested changes
It seems good in my testing 👍

2022-03-08 00:18 UTC, mistval commented on bot/src/bot_settings.js
> +function onShiritoriForeverDakutenChanged() {}
I think we can delete these, and just omit the property from the settings.

2022-03-08 00:18 UTC, mistval commented on bot/src/bot_settings.js
> +        userFacingName: 'Dakuten',
Maybe "Lax dakuten" would be a more descriptive setting name?

2022-03-08 00:18 UTC, mistval commented on node-common/shiritori/japanese_game_strategy.js
> +  console.log(settings, currentWordReading);
Let's remove the log statements (there's another one a little ways down too)

2022-03-08 00:18 UTC, mistval commented on node-common/shiritori/japanese_game_strategy.js
> +    a = getNextWordMustStartWith(dupSettings, currentWordReading);
Could we give this a more descriptive name than `a`?

2022-03-08 01:18 UTC, Riolku commented
So sorry for pushing code with some debug stuff leftover... Updated now.

2022-03-08 01:20 UTC, Riolku commented
Sort of related, this function would really benefit from unit testing (though I'm much too lazy to set that up)...

2022-03-08 01:27 UTC, merged

2022-03-08 01:28 UTC, mistval commented
> Sort of related, this function would really benefit from unit testing (though I'm much too lazy to set that up...)

Me too 😉I will let you know when the changes are deployed (probably tonight for the website but I might not get around to the bot until tomorrow).

2022-03-08 02:15 UTC, mistval commented
API and website have been deployed.

2022-03-09 00:57 UTC, mistval commented
The bot has been deployed.